#Python Program for different string functions.

print("---------String functions")
name="Kushal"
str1=name.upper()
print("UpperCase:")
print(name)
print(str1)
print("------------")
print("LowerCase:")
st=name.lower()
print(st)
print("------------")
print("Swap Case:")
s=name.swapcase()
print(s)
print("------------")
print("Letter Function")
h=name.isalpha()
print(h)
print("------------")
print("Join Function")
w=("'hello', 'Kushal', 'Good morning' ")
x='_'.join(w)
print(w)
print(x)